import { useState, useEffect } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import useAuth from "../../hooks/useAuth";

function MyOrders() {
  const { user } = useAuth();
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (user?.email) {
      fetchMyOrders();
    }
  }, [user]);

  const fetchMyOrders = async () => {
    try {
      setLoading(true);
      const response = await fetch(
        `http://localhost:5000/orders/user/${user.email}`
      );
      const data = await response.json();

      if (data.success) {
        setOrders(data.data);
      } else {
        setError("Failed to fetch orders");
      }
    } catch (err) {
      setError("Error connecting to server");
      console.log(err);
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "pending":
        return "orange";
      case "completed":
        return "green";
      case "cancelled":
        return "red";
      default:
        return "gray";
    }
  };

  // PDF Download Function
  const downloadPDF = () => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.text("PawMart - My Orders Report", 14, 22);

    // User Info
    doc.setFontSize(12);
    doc.text(`User: ${user?.displayName || user?.email}`, 14, 35);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 42);
    doc.text(`Total Orders: ${orders.length}`, 14, 49);

    // Table Data
    const tableData = orders.map((order, index) => [
      index + 1,
      order.productName,
      order.category,
      order.price === 0 ? "Free" : `${order.price} BDT`,
      order.quantity,
      order.date,
      order.status?.toUpperCase() || "PENDING",
    ]);

    // Create Table
    autoTable(doc, {
      startY: 55,
      head: [["#", "Product", "Category", "Price", "Qty", "Date", "Status"]],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: [51, 51, 51] },
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.text(
        "Generated by PawMart",
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: "center" }
      );
    }

    // Download
    doc.save(`PawMart_Orders_${new Date().toISOString().split("T")[0]}.pdf`);
  };

  if (loading) {
    return <p>Loading your orders...</p>;
  }

  if (error) {
    return <p style={{ color: "red" }}>{error}</p>;
  }

  return (
    <div>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <h1>My Orders</h1>
        {orders.length > 0 && (
          <button
            onClick={downloadPDF}
            style={{
              padding: "10px 20px",
              backgroundColor: "#333",
              color: "white",
            }}
          >
            Download PDF Report
          </button>
        )}
      </div>

      <p>Total: {orders.length} orders</p>

      {orders.length === 0 ? (
        <p>You have no orders yet.</p>
      ) : (
        <table
          border="1"
          cellPadding="10"
          style={{ marginTop: "20px", width: "100%" }}
        >
          <thead>
            <tr>
              <th>#</th>
              <th>Product</th>
              <th>Category</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Address</th>
              <th>Phone</th>
              <th>Date</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {orders.map((order, index) => (
              <tr key={order._id}>
                <td>{index + 1}</td>
                <td>{order.productName}</td>
                <td>{order.category}</td>
                <td>{order.price === 0 ? "Free" : `৳${order.price}`}</td>
                <td>{order.quantity}</td>
                <td>{order.address}</td>
                <td>{order.phone}</td>
                <td>{order.date}</td>
                <td>
                  <span style={{ color: getStatusColor(order.status) }}>
                    {order.status?.toUpperCase() || "PENDING"}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

export default MyOrders;
